### ISSUE TITLE
RID

### ISSUE THREAD

**Issue by B3astbanana** [Lenalein2001/Lena-Utils#1]
Hey, could you point me to the right area to convert RIDs to how you've done it with idiots list. Thanks :)

**Comment by Lenalein2001** [comment]
Why though? It's not really important unless you want to get these RID's, or to create such list on your own.

**Comment by B3astbanana** [comment]
i wanna make a list of my own

**Comment by Lenalein2001** [comment]
I'd recommend to learn different stuff first then. Search for your own solution or just keep the raw RID's in there.
